### 서스펜딩 함수 활용

순차적으로 `suspend` 함수를 실행시켜보면

~~~kotlin
fun main() = runBlocking {
     val elapsedTime = measureTimeMillis { // 소요된 시간을 Long 형식으로 반환
         val value1 = getRandom1()
         val value2 = getRandom2()
         println("${value1} + ${value2} = ${value1 + value2}")
     }
     println(elapsedTime)
}

suspend fun getRandom1(): Int { // 1초를 기다리고 0~500 사이의 랜덤값을 리턴
    delay(1000)
    return Random.nextInt(0, 500)
}

suspend fun getRandom2(): Int {
    delay(1000)
    return Random.nextInt(0, 500)
}
~~~

실행결과 : <br>
236 + 397 = 633<br>
2011<br>

getRandom1, getRandom2가 순차적으로 호출되면서 랜덤값으로 값이 출력되고, 수행시간이 나온다.<br>
두 함수다 1초를 기다리기 때문에 수행시간이 2초정도 나온다. 위 함수들이 한번에 호출된다면, 효율적인 프로그램이 될 것이다. <br>

### async를 이용해 동시 수행하기
`async` 키워드를 이용하면 동시에 다른 블록을 수행할 수 있다. `launch`와 비슷하게 보이지만<br>
수행 결과를 `await` 키워드를 통해 받을 수 있다는 차이가 있다.<br>

결과를 받아야 한다면 `async`, 결과를 받지 않아도 된다면 `launch`를 선택할 수 있다.<br>
'await' 키워드를 만나면 `async` 블록이 수행이 끝났는지 확인하고, 아직 끝나지 않았다면 `suspend` 되었다<br>
나중에 다시 깨어나고 반환값을 받아온다.

~~~kotlin
fun main() = runBlocking {
     val elapsedTime = measureTimeMillis { // 소요된 시간을 Long 형식으로 반환
         val value1 = async { getRandom1() } // 별도의 코루틴으로 호출
         val value2 = async { getRandom2() } // 별도의 코루틴으로 호출
         // 밑에 프린트문을 주석처리한다면 반환되는 시간초는 매우 적게나온다 나는 34가 나왔다.
         // async는 Deferred 타입 값이 리턴되는데 이 값은 await이 호출되기 전까지 getRandom 함수들은
         // 호출되지 않는다.
         println("${value1.await()} + ${value2.await()} = ${value1.await() + value2.await()}")
         // 수행된 결과를 가져오는 await 함수. 2가지 일을 동시에한다 job.join() + 결과도 가져옴
         // await이 호출되는 과정은 중단점이다.
     }
     println(elapsedTime)
}
~~~

실행결과 : <br>
32 + 454 = 486<br>
1019<br>

두 개의 코드를 한번에 수행시켰기 때문에 수행결과가 1초대로 나온다. async 대신 launch를 사용한다면 값을 가지고 올 수 없다.<br>
`await()`을 사용해야지 getRandom() 함수들을 호출한다. await을 호출할 때마다 중단되고, 계산기 끝날 때 재시작 되서<br>
어떤 작업들이 어떤 순서대로 일어나고, 어떻게 처리되는지 생각할 필요 없이 await을 호출하고 기다리면 된다.<br>
async는 넣는 이유는 호출이 끝난 다음 값을 가져오기 위해서, 그리고 동시에 수행하기 위해 사용할 뿐 함수를 호출하려고 사용하는것이 아니다.<br>
await을 호출하지 않으면 완료까지 기다리기를 하지 않는 job의 일종이다.

### async 게으르게 사용하기
`async` 키워드를 사용하는 순간 코드 블록이 실행을 준비하는데<br>
`async(start = CoroutineStart.LAZY)`로 인자를 전달하면 우리가 원하는 순간 수행을 준비하게 할 수 있다.<br>
이후 `start` 메서드를 이용해 수행을 준비하게 할 수 있다.

~~~kotlin
fun main() = runBlocking {
     val elapsedTime = measureTimeMillis { 
         
         // 코루틴이 만들어지지만 실행 예약을 하지 않는다.
         val value1 = async(start = CoroutineStart.LAZY) { getRandom1() } 
         val value2 = async(start = CoroutineStart.LAZY) { getRandom2() } 
         
         // 실행 예약을 하기 위해 start를 호출하면 async블록들이 수행하기위해 Queue에 올라간다.
         value1.start() // 큐에 수행 예약을 한다. 레이지이기때문에
         value2.start()
         println("${value1.await()} + ${value2.await()} = ${value1.await() + value2.await()}")
        
     }
     println(elapsedTime)
}
~~~
실행결과 : <br>
128 + 368 = 496<br>
1022<br>
실행결과는 비슷한거같다.<br>

### async를 사용한 구조적인 동시성
코드를 수행하다 보면 예외가 발생할 수 있다. 예외가 발생하면 위쪽 코루틴 스코프와 아래쪽 코루틴 스코프가 취소된다.<br>
즉, 예외가 전파된다.

~~~kotlin
fun main() = runBlocking {
     val elapsedTime = measureTimeMillis { 
         
         try {
             doSomething()
         } catch(e: IllegalStateException){
             println("doSomething fauled: $e")
             // 메인함수에 doSomething이 포함되어 있어서 예외가 메인함수까지 전파된다.
         }
        
        
     }
}

suspend fun getRandom1(): Int { // 1초를 기다리고 0~500 사이의 랜덤값을 리턴
    try {
        delay(1000)
    	return Random.nextInt(0, 500)
    } finally {
        println("getRandom1 is cancelled.")
    }
}

suspend fun getRandom2(): Int {
    delay(500)
    throw IllegalStateException()
}

suspend fun doSomething() = coroutineScope { // 부모 코루틴
    val value1 = async { getRandom1() } // 자식 코루틴
    val value2 = async { getRandom2() } // 자식 코루틴
    
    // 예외발생! 예외가 전파돼서 getRandom1까지 cancel된다.
    // coroutneScope에 속해있고 자식으로 속해있다
    // // 자기의 형제, 부모 코루틴 까지 전파됨
    
    try {
        println("${value1.await()} + ${value2.await()} = ${value1.await() + value2.await()}")
    } finally {
        println("doSomething is cancelled.")
    }
}
~~~
실행결과 : <br>
getRandom1 is cancelled.<br>
doSomething is cancelled.<br>
doSomething fauled: java.lang.IllegalStateException<br>

await을 사용하고 사용안하는 시점에서 코드흐름이 잘 이해가 안가는 부분이 많았다.<br>
Deferred 인터페이스의 주석을 보고 이해가갔다.<br>

스레드를 차단하지 않고 이 값이 완료될 때까지 기다렸다가 지연된 계산이 완료되면 다시 시작하여 결과 값을 반환하거나 지연된 항목이 취소된 경우 해당 예외를 throw합니다.(번역)<br>







